config/routes.rb
Rails.application.routes.draw do
  # devise_for :super_admins
  devise_for :super_admins, path: 'super_admins'
  get 'errors/show'
    # Manually overriding the controllers routes in order to use custom ones
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: "users/registrations"}
  namespace :user do
    root :to => "company_licenses#dashboard"
  end
  root to: 'pages#index'

  resources :company_licenses
  get '/dashboard', to: 'company_licenses#dashboard'
  get '/integrations', to: 'integrations#index'
  get '/usage', to: 'company_licenses#usage'
  post '/create_results', to: 'company_licenses#create_results'
  get '/show_results/:vendor_id', to: 'company_licenses#show_results', as: 'show_results'
  # get '/show_results', to: 'company_licenses#show_results', as: 'show_results', :defaults => { :format => 'json' }

  resources :license_usages, only: [:create]
  # post 'usage', to: 'license_usages#create'
  get 'usage/new/:user_id', to: 'license_usages#new', as: 'new_survey'
  get 'usage/survey/:user_id', to: 'license_usages#survey_user', as: 'survey_user'
  get 'usage/survey_all', to: 'license_usages#survey_all', as: 'survey_all'
  get 'usage/survey_missing', to: 'license_usages#survey_missing', as: 'survey_missing'


  # CSV uploader routes
  get '/show_vendors_results', to: 'flatfiles#show_vendors_results'
  get '/show_companies_results', to: 'flatfiles#show_companies_results'
  get '/show_departments_results', to: 'flatfiles#show_departments_results'
  get '/show_users_results', to: 'flatfiles#show_users_results'
  get '/show_contacts_results', to: 'flatfiles#show_contacts_results'
  get '/show_employees_results', to: 'flatfiles#show_employees_results'
  post '/create_department', to: 'flatfiles#create_department'
  post '/create_company', to: 'flatfiles#create_company'
  post '/create_vendor', to: 'flatfiles#create_vendor'
  post '/create_vendor_contact', to: 'flatfiles#create_vendor_contact'
  post '/create_user', to: 'flatfiles#create_user'
  post '/create_employee', to: 'flatfiles#create_employee'

  # Onboarding
  get '/onboarding/welcome', to: 'onboarding#welcome'
  get '/onboarding/select-apps', to: 'onboarding#select_apps'
  post '/onboarding/select-apps', to: 'onboarding#select_apps_create'
  get '/onboarding/define-plans', to: 'onboarding#define_plans'
  post '/onboarding/define-plans', to: 'onboarding#define_plans_create'
  get '/onboarding/add-employees', to: 'onboarding#add_employees'
  post '/onboarding/add-employees', to: 'onboarding#add_employees_create'
  get '/onboarding/associate-users', to: 'onboarding#associate_users'
  post '/onboarding/associate-users', to: 'onboarding#associate_users_create'

  # Admin routes
  get 'admin/dashboard', to: 'admin#dashboard'
  get 'admin' => redirect("admin/dashboard")

  # categories
  get 'admin/categories', to: 'admin#categories_index'
  get 'admin/categories/new', to: 'admin#category_new'
  post 'admin/categories', to: 'admin#category_create'
  get 'admin/categories/:id', to: 'admin#category_show', as: 'admin_category'
  get 'admin/categories/:id/edit', to: 'admin#category_edit', as: 'admin_category_edit'
  patch 'admin/categories/:id', to: 'admin#category_update'
  delete 'admin/categories/:id', to: 'admin#category_destroy'

  # sub categories
  get 'admin/sub-categories', to: 'admin#sub_categories_index'
  get 'admin/sub-categories/new', to: 'admin#sub_category_new'
  post 'admin/sub-categories', to: 'admin#sub_category_create'
  get 'admin/sub-categories/:id', to: 'admin#sub_category_show', as: 'admin_sub_categorie'
  get 'admin/sub-categories/:id/edit', to: 'admin#sub_category_edit', as: 'admin_sub_category_edit'
  patch 'admin/sub-categories/:id', to: 'admin#sub_category_update'
  delete 'admin/sub-categories/:id', to: 'admin#sub_category_destroy'

  # companies
  get 'admin/companies', to: 'admin#companies_index'
  get 'admin/companies/new', to: 'admin#company_new'
  post 'admin/companies', to: 'admin#company_create'
  get 'admin/companies/:id', to: 'admin#company_show', as: 'admin_company'
  get 'admin/companies/:id/edit', to: 'admin#company_edit', as: 'admin_company_edit'
  patch 'admin/companies/:id', to: 'admin#company_update'
  delete 'admin/companies/:id', to: 'admin#company_destroy'

  # company licenses
  get 'admin/company-licenses', to: 'admin#company_licenses_index'
  get 'admin/company-licenses/new', to: 'admin#company_license_new'
  post 'admin/company-licenses', to: 'admin#company_license_create'
  get 'admin/company-licenses/:id', to: 'admin#company_license_show', as: 'admin_company_license'
  get 'admin/company-licenses/:id/edit', to: 'admin#company_license_edit', as: 'admin_company_license_edit'
  patch 'admin/company-licenses/:id', to: 'admin#company_license_update'
  delete 'admin/company-licenses/:id', to: 'admin#company_license_destroy'

  # company license accounts
  get 'admin/company-license-accounts', to: 'admin#company_license_accounts_index'
  get 'admin/company-license-accounts/new', to: 'admin#company_license_account_new'
  post 'admin/company-license-accounts', to: 'admin#company_license_account_create'
  get 'admin/company-license-accounts/:id', to: 'admin#company_license_account_show', as: 'admin_company_license_account'
  get 'admin/company-license-accounts/:id/edit', to: 'admin#company_license_account_edit', as: 'admin_company_license_account_edit'
  patch 'admin/company-license-accounts/:id', to: 'admin#company_license_account_update'
  delete 'admin/company-license-accounts/:id', to: 'admin#company_license_account_destroy'

  # departments
  get 'admin/departments', to: 'admin#departments_index'
  get 'admin/departments/new', to: 'admin#department_new'
  post 'admin/departments', to: 'admin#department_create'
  get 'admin/departments/:id', to: 'admin#department_show', as: 'admin_department'
  get 'admin/departments/:id/edit', to: 'admin#department_edit', as: 'admin_department_edit'
  patch 'admin/departments/:id', to: 'admin#department_update'
  delete 'admin/departments/:id', to: 'admin#department_destroy'

  # plans
  get 'admin/plans', to: 'admin#plans_index'
  get 'admin/plans/new', to: 'admin#plan_new'
  post 'admin/plans', to: 'admin#plan_create'
  get 'admin/plans/:id', to: 'admin#plan_show', as: 'admin_plan'
  get 'admin/plans/:id/edit', to: 'admin#plan_edit', as: 'admin_plan_edit'
  patch 'admin/plans/:id', to: 'admin#plan_update'
  delete 'admin/plans/:id', to: 'admin#plan_destroy'

  # license_transactions
  get 'admin/license-transactions', to: 'admin#license_transactions_index'
  get 'admin/license-transactions/new', to: 'admin#license_transaction_new'
  post 'admin/license-transactions', to: 'admin#license_transaction_create'
  get 'admin/license-transactions/:id', to: 'admin#license_transaction_show', as: 'admin_license_transaction'
  get 'admin/license-transactions/:id/edit', to: 'admin#license_transaction_edit', as: 'admin_license_transaction_edit'
  patch 'admin/license-transactions/:id', to: 'admin#license_transaction_update'
  delete 'admin/license-transactions/:id', to: 'admin#license_transaction_destroy'

  # transaction users
  get 'admin/transaction-users', to: 'admin#transaction_users_index'
  get 'admin/transaction-users/new', to: 'admin#transaction_user_new'
  post 'admin/transaction-users', to: 'admin#transaction_user_create'
  get 'admin/transaction-users/:id', to: 'admin#transaction_user_show', as: 'admin_transaction_user'
  get 'admin/transaction-users/:id/edit', to: 'admin#transaction_user_edit', as: 'admin_transaction_user_edit'
  patch 'admin/transaction-users/:id', to: 'admin#transaction_user_update'
  delete 'admin/transaction-users/:id', to: 'admin#transaction_user_destroy'

  # license_usages
  get 'admin/license-usages', to: 'admin#license_usages_index'
  get 'admin/license-usages/new', to: 'admin#license_usage_new'
  post 'admin/license-usages', to: 'admin#license_usage_create'
  get 'admin/license-usages/:id', to: 'admin#license_usage_show', as: 'admin_license_usage'
  get 'admin/license-usages/:id/edit', to: 'admin#license_usage_edit', as: 'admin_license_usage_edit'
  patch 'admin/license-usages/:id', to: 'admin#license_usage_update'
  delete 'admin/license-usages/:id', to: 'admin#license_usage_destroy'

  # licenses
  get 'admin/licenses', to: 'admin#licenses_index'
  get 'admin/licenses/new', to: 'admin#license_new'
  post 'admin/licenses', to: 'admin#license_create'
  get 'admin/licenses/:id', to: 'admin#license_show', as: 'admin_license'
  get 'admin/licenses/:id/edit', to: 'admin#license_edit', as: 'admin_license_edit'
  patch 'admin/licenses/:id', to: 'admin#license_update'
  delete 'admin/licenses/:id', to: 'admin#license_destroy'

  # users
  get 'admin/users', to: 'admin#users_index'
  get 'admin/users/new', to: 'admin#user_new'
  post 'admin/users', to: 'admin#user_create'
  get 'admin/users/:id', to: 'admin#user_show', as: 'admin_user'
  get 'admin/users/:id/edit', to: 'admin#user_edit', as: 'admin_user_edit'
  patch 'admin/users/:id', to: 'admin#user_update'
  delete 'admin/users/:id', to: 'admin#user_destroy'

  # vendors
  get 'admin/vendors', to: 'admin#vendors_index'
  get 'admin/vendors/new', to: 'admin#vendor_new'
  post 'admin/vendors', to: 'admin#vendor_create'
  get 'admin/vendors/:id', to: 'admin#vendor_show', as: 'admin_vendor'
  get 'admin/vendors/:id/edit', to: 'admin#vendor_edit', as: 'admin_vendor_edit'
  patch 'admin/vendors/:id', to: 'admin#vendor_update'
  delete 'admin/vendors/:id', to: 'admin#vendor_destroy'

  # vendor contacts
  get 'admin/vendor-contacts', to: 'admin#vendor_contacts_index'
  get 'admin/vendor-contacts/new', to: 'admin#vendor_contact_new'
  post 'admin/vendor-contacts', to: 'admin#vendor_contact_create'
  get 'admin/vendor-contacts/:id', to: 'admin#vendor_contact_show', as: 'admin_vendor_contact'
  get 'admin/vendor-contacts/:id/edit', to: 'admin#vendor_contact_edit', as: 'admin_vendor_contact_edit'
  patch 'admin/vendor-contacts/:id', to: 'admin#vendor_contact_update'

app/views/admin/company_license_account_edit.html.erb
<div class="admin_index_header">
  <h1>Edit Company License Account</h1>
</div>
<div class="half">
  <div>
    <%= simple_form_for(@company_license_account, url: admin_company_license_account_path(@company_license_account)) do |f| %>
      <% if @company_license_account.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @company_license_account.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.input :company_license_id, label: "company_license_id"%>
      <%= f.input :user_id, label: "user_id"%>
      <%= f.input :active, label: "active"%>
      <%= f.input :access_permission, label: "Access Permission"%>
      <%= f.submit 'Create Company License Account', class: 'btn btn-primary',  id: 'booking-btn' %>
    <% end %>
  </div>
</div>

app/views/admin/company_license_account_new.html.erb
<div class="admin_index_header">
  <h1>New Company License Account</h1>
</div>
<div class="half">
  <div>
    <%= simple_form_for(@company_license_account, url: admin_company_license_accounts_path) do |f| %>
      <% if @company_license_account.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @company_license_account.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.input :company_license_id, label: "company_license_id"%>
      <%= f.input :user_id, label: "user_id"%>
      <%= f.input :active, label: "active"%>
      <%= f.input :access_permission, label: "Access Permission"%>
      <%= f.submit 'Create Company License Account', class: 'btn btn-primary',  id: 'booking-btn' %>
    <% end %>
  </div>
  <div class="pathfix-container">
    <h5>Or upload via CSV</h5>
    <button class="btn btn-success">Upload CSV</button>
  </div>
</div>

app/views/admin/company_license_edit.html.erb
<div class="admin_index_header">
  <h1>Edit Company License</h1>
</div>
<div class="half">
  <div>
    <%= simple_form_for(@company_license, url: admin_company_license_path(@company_license)) do |f| %>
      <% if @company_license.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @company_license.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.input :owner_id, label: "owner_id", placeholder: "company_license owner_id" %>
      <%= f.input :plan_id, label: "plan_id", placeholder: "company_license plan_id" %>
      <%= f.input :company_id, label: "company_id", placeholder: "company_license company_id" %>
      <%= f.input :name, label: "Name", placeholder: "company_license name" %>
      <%= f.input :logo, label: "logo", placeholder: "company_license logo" %>
      <%= f.input :sub_category_id, label: "sub_category_id", placeholder: "company_license_id sub_category" %>
      <%= f.submit 'Edit company_license', class: 'btn btn-primary',  id: 'booking-btn' %>
    <% end %>
  </div>
</div>

app/views/admin/company_licenses_index.html.erb
<div class="admin_index_header">
  <div>
    <h1>Company Licenses</h1><span class="count">Total: <%= @company_licenses.count unless !@company_licenses %></span>
  </div>
  <%= link_to "Add Company License", admin_company_licenses_new_path, class: "btn btn-success" %>
</div>
<div>
  <table
    class="card-container table-container table-styled"
    data-toggle="table"
    data-search="true"
    data-sort-name="id"
    data-sort-order="<%= @sort_order %>">
    <thead>
      <tr>
        <th data-field="id" data-sortable="true">Id</th>
        <th data-field="owner_id" data-sortable="true">Owner Id</th>
        <th data-field="plan_id" data-sortable="true">Plan Id</th>
        <th data-field="company_id" data-sortable="true">Company Id</th>
        <th data-field="name" data-sortable="true">Name</th>
        <th data-field="logo" data-sortable="true">Logo</th>
        <th data-field="sub_category_id" data-sortable="true">Sub Category Id</th>
        <th data-field="actions" class="table-action-td"></th>
      </tr>
      <tbody>
        <% unless !@company_licenses || @company_licenses.empty? %>
          <% @company_licenses.each do |company_license| %>
            <tr>
              <%= link_to admin_dashboard_path do %>
                <td><%= company_license.id %></td>
                <td><%= company_license.owner_id %> <span class="light ml-2"><%= company_license.user.email %></span></td>
                <td><%= company_license.plan_id %> <span class="light ml-2"><%= company_license.plan.name %></span></td>
                <td><%= company_license.company_id %> <span class="light ml-2"><%= company_license.company.name %></span></td>
                <td><%= company_license.name %></td>
                <td><%= company_license.logo %></td>
                <td><%= company_license.sub_category_id %><span class="light ml-2"><%= company_license.sub_category.name %></span></td>
                <td class="table-action-td">
                  <%= link_to admin_company_license_path(company_license), class: "table-icon-link" do %>
                    <svg width="20" height="12" viewBox="0 0 20 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M12.9974 5.99886C12.9974 7.58771 11.653 8.87572 9.99457 8.87572C8.33617 8.87572 6.99177 7.58771 6.99177 5.99886C6.99177 4.40999 8.33617 3.12199 9.99457 3.12199C11.653 3.12197 12.9974 4.41001 12.9974 5.99886ZM10 0.00878906C8.28292 0.0164057 6.5031 0.434423 4.81827 1.23474C3.5673 1.85344 2.34817 2.72634 1.2899 3.80376C0.770133 4.35374 0.107183 5.15011 0 5.99979C0.0126667 6.73581 0.802167 7.64427 1.2899 8.19584C2.28228 9.23094 3.46967 10.0795 4.81827 10.7655C6.38945 11.528 8.12853 11.967 10 11.9914C11.7187 11.9837 13.4981 11.5609 15.1811 10.7655C16.4321 10.1468 17.6518 9.27326 18.7101 8.19584C19.2299 7.64586 19.8928 6.84947 20 5.99979C19.9873 5.26377 19.1978 4.35527 18.7101 3.80372C17.7177 2.76862 16.5297 1.92074 15.1811 1.23471C13.6107 0.472772 11.8674 0.0367724 10 0.00878906ZM9.99873 1.49626C12.6007 1.49626 14.71 3.51282 14.71 6.00044C14.71 8.48804 12.6007 10.5046 9.99873 10.5046C7.39675 10.5046 5.28748 8.48802 5.28748 6.00044C5.28748 3.51282 7.39675 1.49626 9.99873 1.49626Z" fill="#838FA0"/>
                    </svg>
                  <% end %>
                  <%= link_to admin_company_license_edit_path(company_license), class: "table-icon-link" do %>
                    <svg width="13" height="13" viewBox="0 0 13 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 10.5V13H2.5L9.87333 5.62662L7.37333 3.12662L0 10.5ZM11.8067 3.69329C12.0667 3.43329 12.0667 3.01329 11.8067 2.75329L10.2467 1.19329C9.98667 0.933291 9.56667 0.933291 9.30667 1.19329L8.08667 2.41329L10.5867 4.91329L11.8067 3.69329Z" fill="#838FA0"/>
                    </svg>
                  <% end %>
                  <%= link_to admin_company_license_path(company_license),
                    method: :delete,
                    data: { confirm: "Are you sure?"},
                    class: "table-icon-link" do %>
                    <svg width="10" height="12" viewBox="0 0 10 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0.999674 10.6667C0.999674 11.4 1.59967 12 2.33301 12H7.66634C8.39967 12 8.99967 11.4 8.99967 10.6667V2.66667H0.999674V10.6667ZM9.66634 0.666667H7.33301L6.66634 0H3.33301L2.66634 0.666667H0.333008V2H9.66634V0.666667Z" fill="#838FA0"/>
                    </svg>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </thead>
  </table>
</div>

app/views/admin/company_new.html.erb
<div class="admin_index_header">
  <h1>New Company</h1>
</div>
<div class="half">
  <div>
    <%= simple_form_for(@company, url: admin_companies_path) do |f| %>
      <% if @company.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @company.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.input :name, label: "Name", placeholder: "company name" %>
      <%= f.input :website, label: "Website", placeholder: "company website" %>
      <%= f.input :address, label: "Address", placeholder: "company address" %>
      <%= f.input :city, label: "City", placeholder: "City" %>
      <%= f.input :postal_zip, label: "Postal Zip Code", placeholder: "Postal zip" %>
      <%= f.input :country, as: :string, label: "Country", placeholder: "Country" %>
      <%= f.submit 'Create company', class: 'btn btn-primary',  id: 'booking-btn' %>
    <% end %>
  </div>
  <div class="pathfix-container">
    <h5>Or upload via CSV</h5>
    <button class="btn btn-success">Upload CSV</button>
  </div>
</div>

app/views/admin/license_new.html.erb
<div class="admin_index_header">
  <h1>New License</h1>
</div>
<div class="half">
  <div>
  </div>
  <div class="pathfix-container">
    <h5>Or upload via CSV</h5>
    <button class="btn btn-success">Upload CSV</button>
  </div>
</div>

app/views/admin/license_transactions_index.html.erb
<div class="admin_index_header">
  <div>
    <h1>License Transactions</h1><span class="count">Total: <%= @license_transactions.count unless !@license_transactions %></span>
  </div>
  <%= link_to "Add License Transaction", admin_license_transactions_new_path, class: "btn btn-success" %>
</div>
<div>
  <table
    class="card-container table-container table-styled"
    data-toggle="table"
    data-search="true"
    data-sort-name="id"
    data-sort-order="<%= @sort_order %>">
    <thead>
      <tr>
        <th data-field="id" data-sortable="true">Id</th>
        <th data-field="company_license_id" data-sortable="true">Compay License Id</th>
        <th data-field="owner_id" data-sortable="true">Owner Id</th>
        <th data-field="total_purchase_price" data-sortable="true">Total Purchase Price</th>
        <th data-field="purchase_date" data-sortable="true">Purchase Date</th>
        <th data-field="expiry_date" data-sortable="true">Expiry Date</th>
        <th data-field="actions" class="table-action-td"></th>
      </tr>
      <tbody>
        <% unless !@license_transactions || @license_transactions.empty? %>
          <% @license_transactions.each do |license_transaction| %>
            <tr>
              <%= link_to admin_dashboard_path do %>
                <td><%= license_transaction.id %></td>
                <td><%= license_transaction.company_license_id %></td>
                <td><%= license_transaction.owner_id %> <span class="light ml-2"><%= license_transaction.owner.email %></span></td>
                <td><%= license_transaction.total_purchase_price %></td>
                <td><%= license_transaction.purchase_date %></td>
                <td><%= license_transaction.expiry_date %></td>
                <td class="table-action-td">
                  <%= link_to admin_license_transaction_path(license_transaction), class: "table-icon-link" do %>
                    <svg width="20" height="12" viewBox="0 0 20 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M12.9974 5.99886C12.9974 7.58771 11.653 8.87572 9.99457 8.87572C8.33617 8.87572 6.99177 7.58771 6.99177 5.99886C6.99177 4.40999 8.33617 3.12199 9.99457 3.12199C11.653 3.12197 12.9974 4.41001 12.9974 5.99886ZM10 0.00878906C8.28292 0.0164057 6.5031 0.434423 4.81827 1.23474C3.5673 1.85344 2.34817 2.72634 1.2899 3.80376C0.770133 4.35374 0.107183 5.15011 0 5.99979C0.0126667 6.73581 0.802167 7.64427 1.2899 8.19584C2.28228 9.23094 3.46967 10.0795 4.81827 10.7655C6.38945 11.528 8.12853 11.967 10 11.9914C11.7187 11.9837 13.4981 11.5609 15.1811 10.7655C16.4321 10.1468 17.6518 9.27326 18.7101 8.19584C19.2299 7.64586 19.8928 6.84947 20 5.99979C19.9873 5.26377 19.1978 4.35527 18.7101 3.80372C17.7177 2.76862 16.5297 1.92074 15.1811 1.23471C13.6107 0.472772 11.8674 0.0367724 10 0.00878906ZM9.99873 1.49626C12.6007 1.49626 14.71 3.51282 14.71 6.00044C14.71 8.48804 12.6007 10.5046 9.99873 10.5046C7.39675 10.5046 5.28748 8.48802 5.28748 6.00044C5.28748 3.51282 7.39675 1.49626 9.99873 1.49626Z" fill="#838FA0"/>
                    </svg>
                  <% end %>
                  <%= link_to admin_license_transaction_edit_path(license_transaction), class: "table-icon-link" do %>
                    <svg width="13" height="13" viewBox="0 0 13 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 10.5V13H2.5L9.87333 5.62662L7.37333 3.12662L0 10.5ZM11.8067 3.69329C12.0667 3.43329 12.0667 3.01329 11.8067 2.75329L10.2467 1.19329C9.98667 0.933291 9.56667 0.933291 9.30667 1.19329L8.08667 2.41329L10.5867 4.91329L11.8067 3.69329Z" fill="#838FA0"/>
                    </svg>
                  <% end %>
                  <%= link_to admin_license_transaction_path(license_transaction),
                    method: :delete,
                    data: { confirm: "Are you sure?"},
                    class: "table-icon-link" do %>
                    <svg width="10" height="12" viewBox="0 0 10 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0.999674 10.6667C0.999674 11.4 1.59967 12 2.33301 12H7.66634C8.39967 12 8.99967 11.4 8.99967 10.6667V2.66667H0.999674V10.6667ZM9.66634 0.666667H7.33301L6.66634 0H3.33301L2.66634 0.666667H0.333008V2H9.66634V0.666667Z" fill="#838FA0"/>
                    </svg>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </thead>
  </table>
</div>

app/views/admin/plan_edit.html.erb
<div class="admin_index_header">
  <h1>Edit Plan</h1>
</div>
<div class="half">
  <div>
    <%= simple_form_for(@plan, url: admin_plan_path(@plan)) do |f| %>
      <% if @plan.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @plan.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.input :vendor_id, label: "vendor_id", placeholder: "Plan vendor_id" %>
      <%= f.input :price, label: "price", placeholder: "Plan price" %>
      <%= f.input :users_capacity, label: "users_capacity", placeholder: "Plan users_capacity" %>
      <%= f.input :name, label: "Name", placeholder: "Plan name" %>
      <%= f.input :description, label: "description", placeholder: "Plan description" %>
      <%= f.input :billing_cycle, label: "billing_cycle", placeholder: "Plan billing_cycle" %>
      <%= f.input :currency, label: "currency", placeholder: "Plan currency" %>
      <%= f.input :cancellation, label: "cancellation", placeholder: "Vendor cancellation" %>
      <%= f.input :product_line, label: "product_line", placeholder: "Vendor product_line" %>
      <%= f.submit 'Edit Plan', class: 'btn btn-primary',  id: 'booking-btn' %>
    <% end %>
  </div>
</div>

app/views/admin/plan_new.html.erb
<div class="admin_index_header">
  <h1>New Plan</h1>
</div>
<div class="half">
  <div>
    <%= simple_form_for(@plan, url: admin_plans_path) do |f| %>
      <% if @plan.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @plan.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.association :vendor, label: "vendor_id", placeholder: "Plan vendor_id", prompt: "Choose a Vendor" %>
      <%= f.input :price, label: "price", placeholder: "Plan price" %>
      <%= f.input :users_capacity, label: "users_capacity", placeholder: "Plan users_capacity" %>
      <%= f.input :name, label: "Name", placeholder: "Plan name" %>
      <%= f.input :description, label: "description", placeholder: "Plan description" %>
      <%= f.input :billing_cycle, label: "billing_cycle", placeholder: "Plan billing_cycle" %>
      <%= f.input :currency, label: "currency", placeholder: "Plan currency" %>
      <%= f.input :cancellation, label: "cancellation", placeholder: "Plan cancellation" %>
      <%= f.input :product_line, label: "product_line", placeholder: "Plan product_line" %>
      <%= f.submit 'Create Plan', class: 'btn btn-primary',  id: 'booking-btn' %>
    <% end %>
  </div>
  <div class="pathfix-container">
    <h5>Or upload via CSV</h5>
    <button class="btn btn-success">Upload CSV</button>
  </div>
</div>

app/views/admin/plan_show.html.erb
<h1><%= @plan %></h1>