config/routes.rb
Rails.application.routes.draw do
  # devise_for :super_admins
  devise_for :super_admins, path: 'super_admins'
  get 'errors/show'
    # Manually overriding the controllers routes in order to use custom ones
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: "users/registrations"}
  namespace :user do
    root :to => "company_licenses#dashboard"
  end
  root to: 'pages#index'

  resources :company_licenses
  get '/dashboard', to: 'company_licenses#dashboard'
  get '/integrations', to: 'integrations#index'
  get '/usage', to: 'company_licenses#usage'
  post '/create_results', to: 'company_licenses#create_results'
  get '/show_results/:vendor_id', to: 'company_licenses#show_results', as: 'show_results'
  # get '/show_results', to: 'company_licenses#show_results', as: 'show_results', :defaults => { :format => 'json' }

  resources :license_usages, only: [:create]
  # post 'usage', to: 'license_usages#create'
  get 'usage/new/:user_id', to: 'license_usages#new', as: 'new_survey'
  get 'usage/survey/:user_id', to: 'license_usages#survey_user', as: 'survey_user'
  get 'usage/survey_all', to: 'license_usages#survey_all', as: 'survey_all'
  get 'usage/survey_missing', to: 'license_usages#survey_missing', as: 'survey_missing'


  # CSV uploader routes
  get '/show_vendors_results', to: 'flatfiles#show_vendors_results'
  get '/show_companies_results', to: 'flatfiles#show_companies_results'
  get '/show_departments_results', to: 'flatfiles#show_departments_results'
  get '/show_users_results', to: 'flatfiles#show_users_results'
  get '/show_contacts_results', to: 'flatfiles#show_contacts_results'
  get '/show_employees_results', to: 'flatfiles#show_employees_results'
  post '/create_department', to: 'flatfiles#create_department'
  post '/create_company', to: 'flatfiles#create_company'
  post '/create_vendor', to: 'flatfiles#create_vendor'
  post '/create_vendor_contact', to: 'flatfiles#create_vendor_contact'
  post '/create_user', to: 'flatfiles#create_user'
  post '/create_employee', to: 'flatfiles#create_employee'

  # Onboarding
  get '/onboarding/welcome', to: 'onboarding#welcome'
  get '/onboarding/select-apps', to: 'onboarding#select_apps'
  post '/onboarding/select-apps', to: 'onboarding#select_apps_create'
  get '/onboarding/define-plans', to: 'onboarding#define_plans'
  post '/onboarding/define-plans', to: 'onboarding#define_plans_create'
  get '/onboarding/add-employees', to: 'onboarding#add_employees'
  post '/onboarding/add-employees', to: 'onboarding#add_employees_create'
  get '/onboarding/associate-users', to: 'onboarding#associate_users'
  post '/onboarding/associate-users', to: 'onboarding#associate_users_create'

  # Admin routes
  get 'admin/dashboard', to: 'admin#dashboard'
  get 'admin' => redirect("admin/dashboard")

  # categories
  get 'admin/categories', to: 'admin#categories_index'
  get 'admin/categories/new', to: 'admin#category_new'
  post 'admin/categories', to: 'admin#category_create'
  get 'admin/categories/:id', to: 'admin#category_show', as: 'admin_category'
  get 'admin/categories/:id/edit', to: 'admin#category_edit', as: 'admin_category_edit'
  patch 'admin/categories/:id', to: 'admin#category_update'
  delete 'admin/categories/:id', to: 'admin#category_destroy'

  # sub categories
  get 'admin/sub-categories', to: 'admin#sub_categories_index'
  get 'admin/sub-categories/new', to: 'admin#sub_category_new'
  post 'admin/sub-categories', to: 'admin#sub_category_create'
  get 'admin/sub-categories/:id', to: 'admin#sub_category_show', as: 'admin_sub_categorie'
  get 'admin/sub-categories/:id/edit', to: 'admin#sub_category_edit', as: 'admin_sub_category_edit'
  patch 'admin/sub-categories/:id', to: 'admin#sub_category_update'
  delete 'admin/sub-categories/:id', to: 'admin#sub_category_destroy'

  # companies
  get 'admin/companies', to: 'admin#companies_index'
  get 'admin/companies/new', to: 'admin#company_new'
  post 'admin/companies', to: 'admin#company_create'
  get 'admin/companies/:id', to: 'admin#company_show', as: 'admin_company'
  get 'admin/companies/:id/edit', to: 'admin#company_edit', as: 'admin_company_edit'
  patch 'admin/companies/:id', to: 'admin#company_update'
  delete 'admin/companies/:id', to: 'admin#company_destroy'

  # company licenses
  get 'admin/company-licenses', to: 'admin#company_licenses_index'
  get 'admin/company-licenses/new', to: 'admin#company_license_new'
  post 'admin/company-licenses', to: 'admin#company_license_create'
  get 'admin/company-licenses/:id', to: 'admin#company_license_show', as: 'admin_company_license'
  get 'admin/company-licenses/:id/edit', to: 'admin#company_license_edit', as: 'admin_company_license_edit'
  patch 'admin/company-licenses/:id', to: 'admin#company_license_update'
  delete 'admin/company-licenses/:id', to: 'admin#company_license_destroy'

  # company license accounts
  get 'admin/company-license-accounts', to: 'admin#company_license_accounts_index'
  get 'admin/company-license-accounts/new', to: 'admin#company_license_account_new'
  post 'admin/company-license-accounts', to: 'admin#company_license_account_create'
  get 'admin/company-license-accounts/:id', to: 'admin#company_license_account_show', as: 'admin_company_license_account'
  get 'admin/company-license-accounts/:id/edit', to: 'admin#company_license_account_edit', as: 'admin_company_license_account_edit'
  patch 'admin/company-license-accounts/:id', to: 'admin#company_license_account_update'
  delete 'admin/company-license-accounts/:id', to: 'admin#company_license_account_destroy'

  # departments
  get 'admin/departments', to: 'admin#departments_index'
  get 'admin/departments/new', to: 'admin#department_new'
  post 'admin/departments', to: 'admin#department_create'
  get 'admin/departments/:id', to: 'admin#department_show', as: 'admin_department'
  get 'admin/departments/:id/edit', to: 'admin#department_edit', as: 'admin_department_edit'
  patch 'admin/departments/:id', to: 'admin#department_update'
  delete 'admin/departments/:id', to: 'admin#department_destroy'

  # plans
  get 'admin/plans', to: 'admin#plans_index'
  get 'admin/plans/new', to: 'admin#plan_new'
  post 'admin/plans', to: 'admin#plan_create'
  get 'admin/plans/:id', to: 'admin#plan_show', as: 'admin_plan'
  get 'admin/plans/:id/edit', to: 'admin#plan_edit', as: 'admin_plan_edit'
  patch 'admin/plans/:id', to: 'admin#plan_update'
  delete 'admin/plans/:id', to: 'admin#plan_destroy'

  # license_transactions
  get 'admin/license-transactions', to: 'admin#license_transactions_index'
  get 'admin/license-transactions/new', to: 'admin#license_transaction_new'
  post 'admin/license-transactions', to: 'admin#license_transaction_create'
  get 'admin/license-transactions/:id', to: 'admin#license_transaction_show', as: 'admin_license_transaction'
  get 'admin/license-transactions/:id/edit', to: 'admin#license_transaction_edit', as: 'admin_license_transaction_edit'
  patch 'admin/license-transactions/:id', to: 'admin#license_transaction_update'
  delete 'admin/license-transactions/:id', to: 'admin#license_transaction_destroy'

  # transaction users
  get 'admin/transaction-users', to: 'admin#transaction_users_index'
  get 'admin/transaction-users/new', to: 'admin#transaction_user_new'
  post 'admin/transaction-users', to: 'admin#transaction_user_create'
  get 'admin/transaction-users/:id', to: 'admin#transaction_user_show', as: 'admin_transaction_user'
  get 'admin/transaction-users/:id/edit', to: 'admin#transaction_user_edit', as: 'admin_transaction_user_edit'
  patch 'admin/transaction-users/:id', to: 'admin#transaction_user_update'
  delete 'admin/transaction-users/:id', to: 'admin#transaction_user_destroy'

  # license_usages
  get 'admin/license-usages', to: 'admin#license_usages_index'
  get 'admin/license-usages/new', to: 'admin#license_usage_new'
  post 'admin/license-usages', to: 'admin#license_usage_create'
  get 'admin/license-usages/:id', to: 'admin#license_usage_show', as: 'admin_license_usage'
  get 'admin/license-usages/:id/edit', to: 'admin#license_usage_edit', as: 'admin_license_usage_edit'
  patch 'admin/license-usages/:id', to: 'admin#license_usage_update'
  delete 'admin/license-usages/:id', to: 'admin#license_usage_destroy'

  # licenses
  get 'admin/licenses', to: 'admin#licenses_index'
  get 'admin/licenses/new', to: 'admin#license_new'
  post 'admin/licenses', to: 'admin#license_create'
  get 'admin/licenses/:id', to: 'admin#license_show', as: 'admin_license'
  get 'admin/licenses/:id/edit', to: 'admin#license_edit', as: 'admin_license_edit'
  patch 'admin/licenses/:id', to: 'admin#license_update'
  delete 'admin/licenses/:id', to: 'admin#license_destroy'

  # users
  get 'admin/users', to: 'admin#users_index'
  get 'admin/users/new', to: 'admin#user_new'
  post 'admin/users', to: 'admin#user_create'
  get 'admin/users/:id', to: 'admin#user_show', as: 'admin_user'
  get 'admin/users/:id/edit', to: 'admin#user_edit', as: 'admin_user_edit'
  patch 'admin/users/:id', to: 'admin#user_update'
  delete 'admin/users/:id', to: 'admin#user_destroy'

  # vendors
  get 'admin/vendors', to: 'admin#vendors_index'
  get 'admin/vendors/new', to: 'admin#vendor_new'
  post 'admin/vendors', to: 'admin#vendor_create'
  get 'admin/vendors/:id', to: 'admin#vendor_show', as: 'admin_vendor'
  get 'admin/vendors/:id/edit', to: 'admin#vendor_edit', as: 'admin_vendor_edit'
  patch 'admin/vendors/:id', to: 'admin#vendor_update'
  delete 'admin/vendors/:id', to: 'admin#vendor_destroy'

  # vendor contacts
  get 'admin/vendor-contacts', to: 'admin#vendor_contacts_index'
  get 'admin/vendor-contacts/new', to: 'admin#vendor_contact_new'
  post 'admin/vendor-contacts', to: 'admin#vendor_contact_create'
  get 'admin/vendor-contacts/:id', to: 'admin#vendor_contact_show', as: 'admin_vendor_contact'
  get 'admin/vendor-contacts/:id/edit', to: 'admin#vendor_contact_edit', as: 'admin_vendor_contact_edit'
  patch 'admin/vendor-contacts/:id', to: 'admin#vendor_contact_update'

app/controllers/company_licenses_controller.rb
class CompanyLicensesController < ApplicationController
    before_action :set_company_license, only: [:show, :edit, :update, :destroy]
    skip_before_action :verify_authenticity_token, :only => [:create_results]
  
    def dashboard
      @license_transactions = LicenseTransaction.all
    end
  
    def index
  
    end
  
    def show
    end
  
    def new
      @company_license = CompanyLicense.new
    end
  
    def create
      @company_license = CompanyLicense.new(company_license_params)
      @company_license.user = current_user
  
      if @company_license.save
        redirect_to company_licenses_path
      else
        render new
      end
    end
  
    def edit
    end
  
    def update
      @company_license.update(company_license_params)
  
      redirect_to company_license_path(@company_license)
    end
  
    def destroy
      @company_license.destroy
  
      redirect_to company_licenses_path
    end
  
    def create_results
      puts "THESE ARE MY PARAMS #{params}"
      params[:data].each do |transaction| 
        p "The transaction is explained below"
        p transaction
        @vendor = Vendor.create!(name: transaction[:vendor_name])
  
      end
        if @vendor.save
          p "The vendor is created and saved #{@vendor}"
          p @vendor
          render json:{ redirect_url: show_results_path(@vendor), success: true }
        else
          render json:{ success: false }
        end
  
    end
  
    def show_results
      @vendor = Vendor.find(params[:vendor_id])
    end
  
    def usage
      @users = User.all
      @company_license = CompanyLicense.new
    end
  
    private
  
    def set_company_license
      @company_license = CompanyLicense.find(params[:id])
    end
  
    def company_license_params
      params.require(:company_license).permit(:license_id)
    end
  
  
  
  
    def validate_params
      params.require(:company_license).permit(:vendor_name, :expiry_date)
    end
  end

app/views/company_licenses/partials/_card_actions.html.erb
<div class="big-metrics-card card-actions">
  <div class="metrics-header">
    <div class="header-content">
      <h4>Insights and Actions</h4>
    </div>
  </div>
  <div class="actions-frame">
      <% ["You can cancel unused licenses to reduce the total software subscription cost by 21%", "You can reduce your Slack license costs by 53 %. Mike Peterson's license is the least used.", "7 subscriptions are up for renewal next month for a total cost of €45.100.", "License usage data was last updated and reviewed 187 days ago.", "Engineering (56,5%) and IT (66,7%) are the departments with the most unused licenses.", "Licenses for 7 new applications have been purchased within the last 30 days."].each do |insight| %>
      <div class="action-item">
        <div class="action-left">
          <div class="action-status"></div>
          <p class="action-message"><%= insight %></p>
        </div>
        <div class="action-button">
          <%# <% slack = CompanyLicense.find_by(license_id: License.find_by(name: "Slack")) %> %>
          <%# <%= link_to company_license_path(slack), class: "btn btn-table btn-success btn-action" do %> %>
            See more
          <%# <% end %> %>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/company_licenses/partials/_card_app_info.html.erb
  <div class="big-metrics-card">
    <div class="metrics-header">
      <div class="header-content">
        <h4><%= cardName %></h4>
        <p>Last 12 months</p>
      </div>
      <%= link_to company_licenses_path do %>View All<% end %>
    </div>
    <% apps.each do | app | %>
    <div class="app-info">

      <%= image_tag("#{app.logo}", class: "app-logo") %>

      <div class="app-name"><%= app.key %></div>
      <div class="app-expense"><%= number_to_currency(app.expense, unit: "€ ", separator: ",", delimiter: ".", precision: 0) %></div>
    </div>
    <% end %>
  </div>

app/views/company_licenses/partials/_card_app_top5app.html.erb
  <div class="big-metrics-card">
    <div class="metrics-header">
      <div class="header-content">
        <h4><%= cardName %></h4>
        <p>Last 12 months</p>
      </div>
      <%= link_to 'View All', company_licenses_path(sort: 'expense') %>
    </div>

    <div class="app-info">
     <%= image_tag("#{'vendor-logos/salesforce-logo.svg'}", class: "app-logo") %>
      <div class="app-name">Salesforce</div>
      <div class="app-expense">€ 187.000</div>
    </div>

    <div class="app-info">
     <%= image_tag("#{'vendor-logos/slack-logo.svg'}", class: "app-logo") %>
      <div class="app-name">Slack</div>
      <div class="app-expense">€ 137.000</div>
    </div>

    <div class="app-info">
     <%= image_tag("#{'vendor-logos/dropbox-logo.svg'}", class: "app-logo") %>
      <div class="app-name">Dropbox</div>
      <div class="app-expense">€ 72.000</div>
    </div>

    <div class="app-info">
     <%= image_tag("#{'vendor-logos/microsoft-office-logo.png'}", class: "app-logo") %>
      <div class="app-name">MS Office</div>
      <div class="app-expense">€ 58.800</div>
    </div>

    <div class="app-info">
     <%= image_tag("#{'vendor-logos/zendesk-logo.svg'}", class: "app-logo") %>
      <div class="app-name">Zendesk</div>
      <div class="app-expense">€ 32.000</div>
    </div>


<!--     <%# apps.each do | app | %>
    <div class="app-info">
      <%#= image_tag("#{app.logo}", class: "app-logo") %>
      <div class="app-name">
      <%#= link_to company_license_path(app.id) do %>
        <%#= app.key %>
              <%# end %></div>
      <div class="app-expense"><%#= number_to_currency(app.expense, unit: "€ ", separator: ",", delimiter: ".", precision: 0) %></div>
    </div>
    <%# end %>
 -->  </div>

app/views/company_licenses/partials/_card_app_util.html.erb
    <div class="big-metrics-card">
    <div class="metrics-header">
      <div class="header-content">
        <h4>Highest Potential Savings</h4>
       <!--  <p>Based on the licenses you're under using, you could save <strong>€ 95.154</strong> this month.</p> -->
      </div>

      <%= link_to 'View All', company_licenses_path(sort: 'util') %>

    </div>


      <div class="app-info">
        <div class="app-name no-left-margin">Application</div>
        <!-- <div class="app-headcount app-item">Head Count</div> -->
        <div class="app-utilization app-item">License Usage</div>
        <div class="app-savings app-item">Potential Saving</div>
      </div>

    <%# @utilization_per_app.each_with_index do |license, index| %>
      <!-- <div class="app-info"> -->

        <%#= image_tag("#{license[:logo_url]}", class: "app-logo") %>

        <!-- <div class="app-name">
          <%#= link_to company_license_path(@utilization_per_app[index][:id]) do %>
          <%#= license[:application] %>
          <%# end %>
        </div>

        <div class="app-headcount app-item"><%#= license[:usage] %>/<%#= license[:capacity] %></div> -->
        <!-- <div class="app-utilization app-item"><%#= license[:utilization] %>%</div>
        <div class="app-savings app-item">
          <%# potentialSaving = (100 - license[:utilization].to_i) * license[:expense].to_i / 100 %>
          <%# if potentialSaving > 100000 %>
            <span class="badge badge-pill badge-danger"><%#= number_to_currency(potentialSaving, unit: "€ ", separator: ",", delimiter: ".", precision: 0) %></span></div>
          <%# elsif potentialSaving > 20000 %>
            <span class="badge badge-pill badge-warning"><%#= number_to_currency(potentialSaving, unit: "€ ", separator: ",", delimiter: ".", precision: 0) %></span></div>
          <%# else %>
            <span class="badge badge-pill badge-primary"><%#= number_to_currency(potentialSaving, unit: "€ ", separator: ",", delimiter: ".", precision: 0) %></span></div>
          <%# end %>
      </div>

    <%# end %>
  </div> -->


<!-- HARDCODING FIX FOR NOW -->

<div class="app-info">
        <%= image_tag("#{'vendor-logos/slack-logo.svg'}", class: "app-logo") %>
        <div class="app-name">
          <%# <% slack = CompanyLicense.find_by(license_id: License.find_by(name: "Slack")) %> %>
          <%# <%= link_to company_license_path(slack) do %> %>
            Slack
          <%# <% end %> %>
        </div>
        <!-- <div class="app-headcount app-item"> 230/420</div> -->
        <div class="app-utilization app-item">53%</div>
        <div class="app-savings app-item"><span class="badge badge-pill badge-danger">€ 51.200</span></div>
      </div>
      <div class="app-info">
        <%= image_tag("#{'vendor-logos/salesforce-logo.svg'}", class: "app-logo") %>
        <div class="app-name">
          <%# <% salesforce = CompanyLicense.find_by(license_id: License.find_by(name: "Salesforce")) %> %>
           <%# <%= link_to company_license_path(salesforce) do %> %>
          Salesforce
          <%# <% end %> %>
        </div>
        <!-- <div class="app-headcount app-item"> 52/60</div> -->
        <div class="app-utilization app-item">87%</div>
        <div class="app-savings app-item"><span class="badge badge-pill badge-warning">€24.310</span></div>
      </div>
      <div class="app-info">
        <%= image_tag("#{'vendor-logos/zendesk-logo.svg'}", class: "app-logo") %>
        <div class="app-name">
         <%# <% zendesk = CompanyLicense.find_by(license_id: License.find_by(name: "Zendesk")) %> %>
           <%# <%= link_to company_license_path(zendesk) do %> %>
          Zendesk
          <%# <% end %> %>
        </div>
        <!-- <div class="app-headcount app-item"> 27/35</div> -->
        <div class="app-utilization app-item">91%</div>
        <div class="app-savings app-item"><span class="badge badge-pill badge-success">€ 7.314</span></div>
      </div>
      <div class="app-info">
        <%= image_tag("#{'vendor-logos/dropbox-logo.svg'}", class: "app-logo") %>
        <div class="app-name">
          <%# <% dropbox = CompanyLicense.find_by(license_id: License.find_by(name: "Dropbox")) %> %>
           <%# <%= link_to company_license_path(dropbox) do %> %>
          Dropbox
          <%# <% end %> %>
        </div>
        <!-- <div class="app-headcount app-item"> 351/370</div> -->
        <div class="app-utilization app-item">92%</div>
        <div class="app-savings app-item"><span class="badge badge-pill badge-success">€ 8.030</span></div>
      </div>
      <div class="app-info">
        <%= image_tag("#{'vendor-logos/gsuite-logo.svg'}", class: "app-logo") %>
        <div class="app-name">
          <%# <% google = CompanyLicense.find_by(license_id: License.find_by(name: "Google Suite")) %> %>
           <%# <%= link_to company_license_path(google) do %> %>
          Gsuite
          <%# <% end %> %>
        </div>
        <!-- <div class="app-headcount app-item"> 500/510</div> -->
        <div class="app-utilization app-item">93%</div>
        <div class="app-savings app-item"><span class="badge badge-pill badge-success"> € 4.300</span></div>
      </div>
    </div>

app/views/company_licenses/partials/_card_department_spend.html.erb
<% apps = (1..5) %>

  <div class="big-metrics-card">
    <div class="metrics-header">
      <div class="header-content">
        <h4>Spent by department</h4>
        <p>Last 12 months</p>
      </div>
      <a href="">View All</a>
    </div>
    <% apps.each do |app| %>
      <div class="app-info">

        <%= image_tag("vendor-logos/adobe-logo.png", class: "app-logo") %>

        <div class="app-name"><%= departmentName %></div>
        <div class="app-expense"><%= appExpense %> $</div>
      </div>
    <% end %>
  </div>

app/views/company_licenses/partials/_card_integrations_btn.html.erb
<div class="big-metrics-card centered">
  <h2 class="card-title"><%= title %></h2>
  <div class="card-img-container">
    <%= image_tag img, alt: "alttext" %>
  </div>
  <p class="m-bottom-30 p-horiz-50"><%= text %></p>
    <%= link_to cta, csv_path, class: "btn btn-big btn-primary white-text"%>
</div>

app/views/company_licenses/partials/_card_integrations_btn_csv.html.erb
<div class="big-metrics-card centered">
  <h2 class="card-title"><%= title %></h2>
  <div class="card-img-container">
    <%= image_tag img, alt: "alttext" %>
  </div>
  <p class="m-bottom-30 p-horiz-50"><%= text %></p>
  <div id="#main">
  <input type="button" id="<%=button_id%>" class="btn btn-big btn-primary white-text" value="Import file" />
  </div>
</div>

app/views/company_licenses/partials/_card_renewals_calendar.html.erb
<div class="big-metrics-card">

  <%= month_calendar(events: @license_transactions, attribute: :expiry_date) do |date, license_transactions| %>

    <div class="day-number">
      <%= date.day %>
    </div>

    <div class="day-renewal-sum">

      <% license_transactions.each do |license_transaction| %>

        <div class="app-info-tip">

        <%= link_to company_license_path(license_transaction.company_license.license.id) do %>

            <div class="dot">

              <span class="app-info-content">

                <%= license_transaction.company_license.license.name %>
                <br>
                Renewal sum: <%= number_with_delimiter(license_transaction.total_purchase_price, :delimiter => '.') %> €

                <br>
                Expiry date: <%= license_transaction.expiry_date %>
                <br>

      <%#= raise %>

              </span>

            </div>

          <% end %>

        </div>

      <% end %>

    </div>

  <% end %>

</div>

app/views/company_licenses/partials/_cards_metrics_bottom.html.erb
<div class="metrics-cards-container">
  <!-- <div class="metrics-cards-container-row"> -->
  <!-- Spent by top 5 applications -->
  <%#= render partial: "company_licenses/partials/card_app_top5app", locals: {
    cardName: "Spent by top 5 applications", apps: @spend_per_app }%>
  <!-- Spent by department -->
  <%#= render partial: "company_licenses/partials/card_app_spentdepart", locals: {
  cardName: "Spent by Department", apps: @spend_per_department }%>
  <!-- </div> -->
  <div class="metrics-cards-container-row">
  <!-- Utililization - Least used applications -->
  <%= render partial: "company_licenses/partials/card_app_util", locals: {
    apps: @utilization_per_app }%>
  <%= render partial: "company_licenses/partials/card_actions" %>

  <!-- Upcomming renewals - new partial required? -->
  <%#= render partial: "company_licenses/partials/card_renewals_calendar", locals: {
  cardName: "Upcomming renewals", apps: Hash.new(3) }%>
  </div>
</div>

app/views/company_licenses/partials/_table-department.html.erb
<table
  class="card-container table-container table-styled"
  data-toggle="table"
  data-search="true"
  data-sort-name="name">
  <thead>
    <tr>
      <th data-field="user" data-sortable="true">User</th>
      <th data-field="email" data-sortable="true">Email</th>
      <th data-field="role" data-sortable="true">Role</th>
      <th data-field="lupdated" data-sortable="true">Last updated</th>
      <th data-field="NApps" data-sortable="true">N. Applications</th>
      <th data-field="Actions"></th>
    </tr>
    <tbody>
      <% users.each do |user| %>
      <tr>
        <td class="table-row-name"><%= user.first_name %> <%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= ["Accountant", "Sales Manager", "Copywriting", "CMO", "Digital Marketing Specialist"].sample %></td>
        <td>
          <%# <% if !user.usage_survey_completed %> %>
            <%# <span class="badge badge-warning">Missing usage data</span> %>
          <%# <% else %> %>
            <%# <%= user.usage_survey_completed.strftime("%B %d, %Y") %> %>
          <%# <% end %> %>
          </td>
        <td>
          <%# <% if !user.usage_survey_completed %> %>
            <%# <span class="badge badge-warning">Missing usage data</span> %>
          <%# <% else %> %>
             <%# <%= user.license_usages.count(:company_license_id) %></td> %>
          <%# <% end %> %>
        <td class="table-action-td">
          <%= link_to survey_user_path(user), class: "btn btn-table btn-success" do %>
            <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M10 2H2C1.45 2 1.005 2.45 1.005 3L1 9C1 9.55 1.45 10 2 10H10C10.55 10 11 9.55 11 9V3C11 2.45 10.55 2 10 2ZM10 4L6 6.5L2 4V3L6 5.5L10 3V4Z" fill="white"/>
            </svg>
            Send survey
          <% end %>
          <%= link_to usage_path do %>
            <svg width="13" height="13" viewBox="0 0 13 13" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 10.5V13H2.5L9.87333 5.62662L7.37333 3.12662L0 10.5ZM11.8067 3.69329C12.0667 3.43329 12.0667 3.01329 11.8067 2.75329L10.2467 1.19329C9.98667 0.933291 9.56667 0.933291 9.30667 1.19329L8.08667 2.41329L10.5867 4.91329L11.8067 3.69329Z" fill="#C2CFE0"/>
            </svg>
          <% end %>
          <%= link_to usage_path do %>
            <svg width="10" height="12" viewBox="0 0 10 12" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0.999674 10.6667C0.999674 11.4 1.59967 12 2.33301 12H7.66634C8.39967 12 8.99967 11.4 8.99967 10.6667V2.66667H0.999674V10.6667ZM9.66634 0.666667H7.33301L6.66634 0H3.33301L2.66634 0.666667H0.333008V2H9.66634V0.666667Z" fill="#C2CFE0"/>
            </svg>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </thead>
</table>