config/routes.rb
Rails.application.routes.draw do
  # devise_for :super_admins
  devise_for :super_admins, path: 'super_admins'
  get 'errors/show'
    # Manually overriding the controllers routes in order to use custom ones
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: "users/registrations"}
  namespace :user do
    root :to => "company_licenses#dashboard"
  end
  root to: 'pages#index'

  resources :company_licenses
  get '/dashboard', to: 'company_licenses#dashboard'
  get '/integrations', to: 'integrations#index'
  get '/usage', to: 'company_licenses#usage'
  post '/create_results', to: 'company_licenses#create_results'
  get '/show_results/:vendor_id', to: 'company_licenses#show_results', as: 'show_results'
  # get '/show_results', to: 'company_licenses#show_results', as: 'show_results', :defaults => { :format => 'json' }

  resources :license_usages, only: [:create]
  # post 'usage', to: 'license_usages#create'
  get 'usage/new/:user_id', to: 'license_usages#new', as: 'new_survey'
  get 'usage/survey/:user_id', to: 'license_usages#survey_user', as: 'survey_user'
  get 'usage/survey_all', to: 'license_usages#survey_all', as: 'survey_all'
  get 'usage/survey_missing', to: 'license_usages#survey_missing', as: 'survey_missing'


  # CSV uploader routes
  get '/show_vendors_results', to: 'flatfiles#show_vendors_results'
  get '/show_companies_results', to: 'flatfiles#show_companies_results'
  get '/show_departments_results', to: 'flatfiles#show_departments_results'
  get '/show_users_results', to: 'flatfiles#show_users_results'
  get '/show_contacts_results', to: 'flatfiles#show_contacts_results'
  get '/show_employees_results', to: 'flatfiles#show_employees_results'
  post '/create_department', to: 'flatfiles#create_department'
  post '/create_company', to: 'flatfiles#create_company'
  post '/create_vendor', to: 'flatfiles#create_vendor'
  post '/create_vendor_contact', to: 'flatfiles#create_vendor_contact'
  post '/create_user', to: 'flatfiles#create_user'
  post '/create_employee', to: 'flatfiles#create_employee'

  # Onboarding
  get '/onboarding/welcome', to: 'onboarding#welcome'
  get '/onboarding/select-apps', to: 'onboarding#select_apps'
  post '/onboarding/select-apps', to: 'onboarding#select_apps_create'
  get '/onboarding/define-plans', to: 'onboarding#define_plans'
  post '/onboarding/define-plans', to: 'onboarding#define_plans_create'
  get '/onboarding/add-employees', to: 'onboarding#add_employees'
  post '/onboarding/add-employees', to: 'onboarding#add_employees_create'
  get '/onboarding/associate-users', to: 'onboarding#associate_users'
  post '/onboarding/associate-users', to: 'onboarding#associate_users_create'

  # Admin routes
  get 'admin/dashboard', to: 'admin#dashboard'
  get 'admin' => redirect("admin/dashboard")

  # categories
  get 'admin/categories', to: 'admin#categories_index'
  get 'admin/categories/new', to: 'admin#category_new'
  post 'admin/categories', to: 'admin#category_create'
  get 'admin/categories/:id', to: 'admin#category_show', as: 'admin_category'
  get 'admin/categories/:id/edit', to: 'admin#category_edit', as: 'admin_category_edit'
  patch 'admin/categories/:id', to: 'admin#category_update'
  delete 'admin/categories/:id', to: 'admin#category_destroy'

  # sub categories
  get 'admin/sub-categories', to: 'admin#sub_categories_index'
  get 'admin/sub-categories/new', to: 'admin#sub_category_new'
  post 'admin/sub-categories', to: 'admin#sub_category_create'
  get 'admin/sub-categories/:id', to: 'admin#sub_category_show', as: 'admin_sub_categorie'
  get 'admin/sub-categories/:id/edit', to: 'admin#sub_category_edit', as: 'admin_sub_category_edit'
  patch 'admin/sub-categories/:id', to: 'admin#sub_category_update'
  delete 'admin/sub-categories/:id', to: 'admin#sub_category_destroy'

  # companies
  get 'admin/companies', to: 'admin#companies_index'
  get 'admin/companies/new', to: 'admin#company_new'
  post 'admin/companies', to: 'admin#company_create'
  get 'admin/companies/:id', to: 'admin#company_show', as: 'admin_company'
  get 'admin/companies/:id/edit', to: 'admin#company_edit', as: 'admin_company_edit'
  patch 'admin/companies/:id', to: 'admin#company_update'
  delete 'admin/companies/:id', to: 'admin#company_destroy'

  # company licenses
  get 'admin/company-licenses', to: 'admin#company_licenses_index'
  get 'admin/company-licenses/new', to: 'admin#company_license_new'
  post 'admin/company-licenses', to: 'admin#company_license_create'
  get 'admin/company-licenses/:id', to: 'admin#company_license_show', as: 'admin_company_license'
  get 'admin/company-licenses/:id/edit', to: 'admin#company_license_edit', as: 'admin_company_license_edit'
  patch 'admin/company-licenses/:id', to: 'admin#company_license_update'
  delete 'admin/company-licenses/:id', to: 'admin#company_license_destroy'

  # company license accounts
  get 'admin/company-license-accounts', to: 'admin#company_license_accounts_index'
  get 'admin/company-license-accounts/new', to: 'admin#company_license_account_new'
  post 'admin/company-license-accounts', to: 'admin#company_license_account_create'
  get 'admin/company-license-accounts/:id', to: 'admin#company_license_account_show', as: 'admin_company_license_account'
  get 'admin/company-license-accounts/:id/edit', to: 'admin#company_license_account_edit', as: 'admin_company_license_account_edit'
  patch 'admin/company-license-accounts/:id', to: 'admin#company_license_account_update'
  delete 'admin/company-license-accounts/:id', to: 'admin#company_license_account_destroy'

  # departments
  get 'admin/departments', to: 'admin#departments_index'
  get 'admin/departments/new', to: 'admin#department_new'
  post 'admin/departments', to: 'admin#department_create'
  get 'admin/departments/:id', to: 'admin#department_show', as: 'admin_department'
  get 'admin/departments/:id/edit', to: 'admin#department_edit', as: 'admin_department_edit'
  patch 'admin/departments/:id', to: 'admin#department_update'
  delete 'admin/departments/:id', to: 'admin#department_destroy'

  # plans
  get 'admin/plans', to: 'admin#plans_index'
  get 'admin/plans/new', to: 'admin#plan_new'
  post 'admin/plans', to: 'admin#plan_create'
  get 'admin/plans/:id', to: 'admin#plan_show', as: 'admin_plan'
  get 'admin/plans/:id/edit', to: 'admin#plan_edit', as: 'admin_plan_edit'
  patch 'admin/plans/:id', to: 'admin#plan_update'
  delete 'admin/plans/:id', to: 'admin#plan_destroy'

  # license_transactions
  get 'admin/license-transactions', to: 'admin#license_transactions_index'
  get 'admin/license-transactions/new', to: 'admin#license_transaction_new'
  post 'admin/license-transactions', to: 'admin#license_transaction_create'
  get 'admin/license-transactions/:id', to: 'admin#license_transaction_show', as: 'admin_license_transaction'
  get 'admin/license-transactions/:id/edit', to: 'admin#license_transaction_edit', as: 'admin_license_transaction_edit'
  patch 'admin/license-transactions/:id', to: 'admin#license_transaction_update'
  delete 'admin/license-transactions/:id', to: 'admin#license_transaction_destroy'

  # transaction users
  get 'admin/transaction-users', to: 'admin#transaction_users_index'
  get 'admin/transaction-users/new', to: 'admin#transaction_user_new'
  post 'admin/transaction-users', to: 'admin#transaction_user_create'
  get 'admin/transaction-users/:id', to: 'admin#transaction_user_show', as: 'admin_transaction_user'
  get 'admin/transaction-users/:id/edit', to: 'admin#transaction_user_edit', as: 'admin_transaction_user_edit'
  patch 'admin/transaction-users/:id', to: 'admin#transaction_user_update'
  delete 'admin/transaction-users/:id', to: 'admin#transaction_user_destroy'

  # license_usages
  get 'admin/license-usages', to: 'admin#license_usages_index'
  get 'admin/license-usages/new', to: 'admin#license_usage_new'
  post 'admin/license-usages', to: 'admin#license_usage_create'
  get 'admin/license-usages/:id', to: 'admin#license_usage_show', as: 'admin_license_usage'
  get 'admin/license-usages/:id/edit', to: 'admin#license_usage_edit', as: 'admin_license_usage_edit'
  patch 'admin/license-usages/:id', to: 'admin#license_usage_update'
  delete 'admin/license-usages/:id', to: 'admin#license_usage_destroy'

  # licenses
  get 'admin/licenses', to: 'admin#licenses_index'
  get 'admin/licenses/new', to: 'admin#license_new'
  post 'admin/licenses', to: 'admin#license_create'
  get 'admin/licenses/:id', to: 'admin#license_show', as: 'admin_license'
  get 'admin/licenses/:id/edit', to: 'admin#license_edit', as: 'admin_license_edit'
  patch 'admin/licenses/:id', to: 'admin#license_update'
  delete 'admin/licenses/:id', to: 'admin#license_destroy'

  # users
  get 'admin/users', to: 'admin#users_index'
  get 'admin/users/new', to: 'admin#user_new'
  post 'admin/users', to: 'admin#user_create'
  get 'admin/users/:id', to: 'admin#user_show', as: 'admin_user'
  get 'admin/users/:id/edit', to: 'admin#user_edit', as: 'admin_user_edit'
  patch 'admin/users/:id', to: 'admin#user_update'
  delete 'admin/users/:id', to: 'admin#user_destroy'

  # vendors
  get 'admin/vendors', to: 'admin#vendors_index'
  get 'admin/vendors/new', to: 'admin#vendor_new'
  post 'admin/vendors', to: 'admin#vendor_create'
  get 'admin/vendors/:id', to: 'admin#vendor_show', as: 'admin_vendor'
  get 'admin/vendors/:id/edit', to: 'admin#vendor_edit', as: 'admin_vendor_edit'
  patch 'admin/vendors/:id', to: 'admin#vendor_update'
  delete 'admin/vendors/:id', to: 'admin#vendor_destroy'

  # vendor contacts
  get 'admin/vendor-contacts', to: 'admin#vendor_contacts_index'
  get 'admin/vendor-contacts/new', to: 'admin#vendor_contact_new'
  post 'admin/vendor-contacts', to: 'admin#vendor_contact_create'
  get 'admin/vendor-contacts/:id', to: 'admin#vendor_contact_show', as: 'admin_vendor_contact'
  get 'admin/vendor-contacts/:id/edit', to: 'admin#vendor_contact_edit', as: 'admin_vendor_contact_edit'
  patch 'admin/vendor-contacts/:id', to: 'admin#vendor_contact_update'

app/views/layouts/application.htmldefault.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/onboarding.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= if content_for?(:title) then yield(:title) + ' | ' end %>Overblik</title>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>

    <div class="admin_header">
      <div class="admin_header_left">
        <span>
          <svg width="110" height="30" viewBox="0 0 111 23" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M0 15.2414C0 14.2074 0.191728 13.2884 0.613528 12.3693C1.03533 11.4885 1.61051 10.7226 2.33908 10.0716C3.06764 9.42055 3.94959 8.92271 4.94657 8.53976C5.94355 8.15681 7.05557 7.96533 8.24428 7.96533C9.433 7.96533 10.5067 8.15681 11.542 8.50146C12.539 8.88442 13.4209 9.38225 14.1878 10.0333C14.9547 10.6843 15.4916 11.4502 15.9134 12.3693C16.3352 13.2884 16.5269 14.284 16.5269 15.3563C16.5269 16.4286 16.3352 17.4242 15.9134 18.3433C15.4916 19.2624 14.9164 20.0283 14.1878 20.6793C13.4593 21.3303 12.5773 21.8282 11.542 22.2111C10.5067 22.5558 9.39465 22.7472 8.20594 22.7472C7.01723 22.7472 5.94355 22.5558 4.94657 22.2111C3.94959 21.8665 3.06764 21.3303 2.33908 20.6793C1.61051 20.0283 1.03533 19.2241 0.651874 18.305C0.191728 17.3859 0 16.3903 0 15.2414ZM5.1383 15.318C5.1383 15.7775 5.21499 16.1988 5.40672 16.5817C5.5601 16.9647 5.79017 17.3093 6.09694 17.5774C6.36535 17.8455 6.71046 18.0752 7.09392 18.2667C7.47737 18.4199 7.89918 18.4965 8.32098 18.4965C8.74278 18.4965 9.16458 18.4199 9.54803 18.2667C9.93149 18.1135 10.2766 17.8838 10.545 17.5774C10.8134 17.271 11.0435 16.9647 11.2352 16.5817C11.427 16.1988 11.5037 15.7775 11.5037 15.318C11.5037 14.8967 11.427 14.4755 11.2352 14.0925C11.0819 13.7096 10.8518 13.3649 10.545 13.0969C10.2766 12.8288 9.93149 12.599 9.54803 12.4076C9.16458 12.2544 8.74278 12.1778 8.32098 12.1778C7.89918 12.1778 7.47737 12.2544 7.09392 12.4076C6.71046 12.5607 6.36535 12.7905 6.09694 13.0969C5.82852 13.3649 5.59844 13.7096 5.40672 14.0925C5.21499 14.4755 5.1383 14.8585 5.1383 15.318Z" fill="#393836"/>
          <path d="M21.7805 8.84612L26.2669 21.5601C26.3819 21.9048 26.1518 22.2494 25.7684 22.2494H21.9722C21.7421 22.2494 21.5887 22.1345 21.512 21.943L16.4504 9.19078C16.297 8.84612 16.5655 8.50146 16.9106 8.50146H21.2436C21.512 8.50146 21.7038 8.61635 21.7805 8.84612Z" fill="#FFBF00"/>
          <path d="M32.4401 0.0766602H36.6964C37.0799 0.0766602 37.3483 0.497906 37.1566 0.842562L26.2665 21.9815C26.1898 22.1346 25.998 22.2495 25.8063 22.2495H22.0868C21.7033 22.2495 21.4733 21.8666 21.6267 21.5219L31.9799 0.383021C32.0566 0.191545 32.2484 0.0766602 32.4401 0.0766602Z" fill="#26B5F8"/>
          <path d="M38.2688 16.1988C38.0387 16.1988 37.8086 16.4286 37.847 16.6583C38.0003 18.4582 38.959 19.339 40.7996 19.339C41.7582 19.339 42.5251 18.956 43.062 18.2284C43.1386 18.1135 43.2537 18.0369 43.4071 18.0369H47.28C47.5867 18.0369 47.7784 18.3433 47.6634 18.6114C46.5897 21.3686 44.289 22.7472 40.7612 22.7472C39.6109 22.7472 38.5372 22.5558 37.5785 22.2111C36.6199 21.8665 35.7763 21.3686 35.0861 20.7176C34.3959 20.0666 33.859 19.3007 33.4756 18.4199C33.0921 17.5391 32.9004 16.5434 32.9004 15.4329C32.9004 14.284 33.0921 13.2501 33.4372 12.331C33.7823 11.4119 34.3192 10.646 34.971 9.99497C35.6229 9.34396 36.4282 8.84612 37.3868 8.50146C38.3455 8.15681 39.3808 7.96533 40.5695 7.96533C41.7199 7.96533 42.7935 8.15681 43.7138 8.50146C44.6341 8.84612 45.4394 9.34396 46.0912 10.0333C46.7431 10.6843 47.2416 11.4885 47.5484 12.4459C47.8935 13.4032 48.0469 14.4755 48.0469 15.6626V16.1605L38.2688 16.1988ZM42.9086 13.3649C43.2153 13.3649 43.4071 13.0586 43.292 12.7522C43.1003 12.331 42.8319 11.9863 42.4868 11.7183C41.9883 11.297 41.3747 11.1055 40.6462 11.1055C39.8793 11.1055 39.2657 11.297 38.8056 11.68C38.4605 11.948 38.1921 12.331 38.0387 12.7905C37.962 13.0586 38.1537 13.3266 38.4605 13.3266H42.9086V13.3649Z" fill="#393836"/>
          <path d="M50.1944 8.50146H54.1824C54.4125 8.50146 54.6425 8.69294 54.6425 8.96101V9.49714C54.6425 9.88009 55.141 10.1099 55.4094 9.8035C55.7545 9.42055 56.138 9.15248 56.5598 8.88442C57.3267 8.46317 58.1703 8.2334 59.2056 8.2334C59.3207 8.2334 59.4741 8.2334 59.6274 8.2334C59.7808 8.2334 59.9725 8.2334 60.1643 8.27169V12.2544C60.1643 12.5607 59.8575 12.7522 59.5891 12.6756C59.1289 12.5224 58.6305 12.4459 58.0936 12.4459C56.9816 12.4459 56.138 12.7905 55.5628 13.4415C54.9876 14.0925 54.7192 15.0882 54.7192 16.3903V21.8282C54.7192 22.0579 54.5275 22.2877 54.2591 22.2877H50.2711C50.0411 22.2877 49.811 22.0962 49.811 21.8282V8.92271C49.7343 8.69294 49.926 8.50146 50.1944 8.50146Z" fill="#393836"/>
          <path d="M67.0662 0.421246V8.88447C67.0662 9.22912 67.488 9.45889 67.7564 9.22912C68.7534 8.46322 69.9804 8.04197 71.3609 8.04197C72.3962 8.04197 73.3165 8.23345 74.1601 8.6164C75.0037 8.99935 75.7323 9.53548 76.3458 10.1865C76.9593 10.8375 77.4195 11.6034 77.7646 12.4842C78.1097 13.365 78.2631 14.3224 78.2631 15.318C78.2631 16.352 78.0713 17.3094 77.7262 18.1902C77.3811 19.071 76.8826 19.8752 76.2691 20.5262C75.6556 21.1772 74.8887 21.7133 74.0451 22.0963C73.2015 22.4792 72.2812 22.6707 71.2842 22.6707C69.8654 22.6707 68.715 22.2495 67.7564 21.4453C67.488 21.2155 67.0278 21.407 67.0278 21.7516V21.8282C67.0278 22.058 66.8361 22.2495 66.606 22.2495H62.6181C62.388 22.2495 62.1963 22.058 62.1963 21.8282V0.421246C62.1963 0.191476 62.388 0 62.6181 0H66.606C66.8744 0 67.0662 0.191476 67.0662 0.421246ZM73.2014 15.2415C73.1631 14.8968 73.0864 14.5521 72.9714 14.2075C72.818 13.8245 72.5879 13.4799 72.2812 13.2118C72.0127 12.9437 71.6676 12.714 71.2842 12.5225C70.9007 12.3693 70.4789 12.2544 70.0571 12.2544C69.6353 12.2544 69.2135 12.331 68.8684 12.4842C68.485 12.6374 68.1782 12.8672 67.8714 13.1735C67.603 13.4416 67.3729 13.7862 67.1812 14.1692C67.0278 14.5521 66.9128 14.9734 66.9128 15.3946C66.9128 15.8159 66.9895 16.2371 67.1429 16.6201C67.2962 17.003 67.5263 17.3094 67.8331 17.6158C68.1015 17.8838 68.4466 18.1136 68.8301 18.3051C69.2135 18.4582 69.6353 18.5731 70.0571 18.5731C70.4789 18.5731 70.9007 18.4965 71.2842 18.3434C71.6676 18.1902 71.9744 17.9604 72.2812 17.654C72.4729 17.4243 72.6646 17.1945 72.818 16.9264C73.0864 16.352 73.2398 15.7776 73.2014 15.2415Z" fill="#393836"/>
          <path d="M84.8201 0.382951V21.9048C84.8201 22.0963 84.6667 22.2878 84.4366 22.2878H80.3337C80.1419 22.2878 79.9502 22.1346 79.9502 21.9048V0.382951C79.9502 0.191476 80.1036 0 80.3337 0H84.4366C84.6667 0 84.8201 0.15318 84.8201 0.382951Z" fill="#393836"/>
          <path d="M86.7373 3.21672C86.7373 2.83377 86.814 2.48911 86.9674 2.14446C87.1208 1.7998 87.3125 1.53174 87.5426 1.26367C87.811 0.995604 88.0794 0.804129 88.4245 0.689243C88.7696 0.536063 89.1147 0.459473 89.4982 0.459473C89.8816 0.459473 90.2267 0.536063 90.5719 0.689243C90.917 0.842424 91.1854 1.0339 91.4538 1.26367C91.7222 1.53174 91.9139 1.7998 92.029 2.14446C92.1824 2.48911 92.2591 2.83377 92.2591 3.21672C92.2591 3.59967 92.1824 3.94433 92.029 4.28898C91.8756 4.63364 91.6839 4.90171 91.4538 5.16977C91.1854 5.43784 90.917 5.62931 90.5719 5.7442C90.2267 5.89738 89.8816 5.97397 89.4982 5.97397C89.1147 5.97397 88.7696 5.89738 88.4245 5.7442C88.0794 5.59102 87.811 5.39954 87.5426 5.16977C87.2741 4.90171 87.0824 4.63364 86.9674 4.28898C86.814 3.94433 86.7373 3.59967 86.7373 3.21672ZM91.9139 8.8844V21.9047C91.9139 22.0962 91.7606 22.2877 91.5305 22.2877H87.4275C87.2358 22.2877 87.0441 22.1345 87.0441 21.9047V8.8844C87.0441 8.69292 87.1975 8.50145 87.4275 8.50145H91.5305C91.7606 8.50145 91.9139 8.65463 91.9139 8.8844Z" fill="#393836"/>
          <path d="M99.0466 0.382951V12.5991C99.0466 12.9437 99.4301 13.0969 99.6602 12.8672L104.032 8.6164C104.108 8.53981 104.185 8.50151 104.3 8.50151H109.86C110.205 8.50151 110.359 8.92276 110.128 9.15253L104.223 14.5904C104.07 14.7436 104.07 14.9734 104.223 15.1266L110.627 21.6367C110.857 21.8665 110.704 22.2495 110.359 22.2495H104.568C104.453 22.2495 104.377 22.2112 104.3 22.1346L99.6985 17.3094C99.4684 17.0796 99.0466 17.2328 99.0466 17.5775V21.9048C99.0466 22.0963 98.8932 22.2878 98.6632 22.2878H94.5602C94.3685 22.2878 94.1768 22.1346 94.1768 21.9048V0.382951C94.1768 0.191476 94.3301 0 94.5602 0H98.6632C98.8932 0 99.0466 0.15318 99.0466 0.382951Z" fill="#393836"/>
          </svg>
        </span>
      </div>
      <div class="admin_header_right">
      </div>
    </div>
    <div class="admin_container">
      <div class="column w260 onboarding">
        <ul class="progress_list">
          <% check_svg = '<svg width="17" height="14" viewBox="0 0 17 14" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M5.75058 9.02429L2.2201 5.49996L0.0517578 7.67445L5.75365 13.3641L16.0518 3.06595L13.8803 0.894531L5.75058 9.02429Z" fill="#393836"/>
          </svg>
          ' %>
          <li class="<%= 'active' if @progress >= 1 %> <%= 'completed' if @progress > 1 %>"><div class="progress_step_number"><%= @progress > 1 ? check_svg.html_safe : '1' %></div><p>Select Apps</p></li>
          <li class="<%= 'active' if @progress >= 2 %> <%= 'completed' if @progress > 2 %>"><div class="progress_step_number"><%= @progress > 2 ? check_svg.html_safe : '2' %></div><p>Define Plans</p></li>
          <li class="<%= 'active' if @progress >= 3 %> <%= 'completed' if @progress > 3 %>"><div class="progress_step_number"><%= @progress > 3 ? check_svg.html_safe : '3' %></div><p>Add Employees</p></li>
          <li class="<%= 'active' if @progress >= 4 %> <%= 'completed' if @progress > 4 %>"><div class="progress_step_number"><%= @progress > 4 ? check_svg.html_safe : '4' %></div><p>Associate Users</p></li>
        </ul>
        <div class="column_bottom_elements">
          <div class="progress_container">
            <p class="progress_label">Overblik setup</p>
            <div class="progress_bar-container">
              <div class="progress_bar"></div>
            </div>
            <p class="progress_status">25% complete</p>
          </div>
          <%= link_to "Save & Continue", onboarding_welcome_path, class: "btn btn-primary" %>
          <hr>
          <%= link_to onboarding_welcome_path, class: "btn_skip" do %>
            Skip step <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M6 11.8125C9.21094 11.8125 11.8125 9.21094 11.8125 6C11.8125 2.78906 9.21094 0.1875 6 0.1875C2.78906 0.1875 0.1875 2.78906 0.1875 6C0.1875 9.21094 2.78906 11.8125 6 11.8125ZM3.28125 4.96875H6V3.30703C6 3.05625 6.30469 2.92969 6.48047 3.10781L9.15937 5.80078C9.26953 5.91094 9.26953 6.08672 9.15937 6.19687L6.48047 8.89219C6.30234 9.07031 6 8.94375 6 8.69297V7.03125H3.28125C3.12656 7.03125 3 6.90469 3 6.75V5.25C3 5.09531 3.12656 4.96875 3.28125 4.96875Z" fill="white"/>
            </svg>
          <% end %>
        </div>
      </div>
      <div class="admin_content_container">
        <%= render 'shared/flashes' %>
        <div class="container">
          <%= yield %>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>